name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Build Docker Image
        run: docker build -t cypress-test-image .

      - name: Run Cypress Tests Inside Docker
        run: docker run cypress-test-image
