name: Cypress Tests

on:
  push:
    branches:
      - master

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js 20.5.1
        uses: actions/setup-node@v2
        with:
          node-version: '20.5.1'

      - name: Install dependencies
        run: npm ci

      - name: Build Docker Image
        run: docker build -t cypress-test-image .

      - name: Run Cypress Tests Inside Docker
        run: docker run cypress-test-image